#tutte le righe commentate sono messe "in sospensione" solo per verificare la correzione del docker compose
#e per evitare errori finche' non abbiamo dei file da caricare nelle directory preposte
services:
  web:
    image: tomcat:10.1.53-jdk25-temurin
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      #DA SETTARE FILE WAR CORRETTO
      - ./target/OURWEBAPP.war:/usr/local/tomcat/webapps/OURWEBAPP.war
     # - ./tmp/server.xml:/usr/local/tomcat/conf/server.xml
     # - ./logs:/usr/local/tomcat/webapps/my-logs
     # - ./tmp/context.xml:/usr/local/tomcat/webapps.dist/manager/META-INF/context.xml
     # - ./tmp/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml

  db:
    image: postgres:17.9
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=servlet
    secrets:
      - postgres_password
    volumes:
#      - ./data/db:/var/lib/postgresql      HA SENSO FARE BIND??? VOLUME MOLTO PIÙ PULITO
       - postgres_data:/var/lib/postgresql/data
       - ./db/database.sql:/docker-entrypoint-initdb.d/01-init.sql
      #- ./src/main/database/sigirwebapp-insert.sql:/docker-entrypoint-initdb.d/02-data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

secrets:
  postgres_password:
    file: secrets/postgres_password.txt