<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://maven.apache.org/POM/4.0.0"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.swad.taptable</groupId>
    <artifactId>taptable</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>war</packaging>

    <name>TapTable</name>
    <description>TapTable is a web application for the management of a dining, enabling customers to browse and reserve dishes online while providing managers and staff tools to oversee reservations and payments.</description>
    <url>https://bitbucket.org/upd-dei-stud-prj/wa2526-swad/</url>
    <organization>
        <name>SWAD - Scalable Web Application Development</name>
    </organization>

    <developers>
        <developer>
            <id>fbaldan</id>
            <name>Fabio Baldan</name>
            <email>fabio.baldan.1@studenti.unipd.it</email>
        </developer>
        <developer>
            <id>agarberino</id>
            <name>Alvise Garberino</name>
            <email>alvise.garberino@studenti.unipd.it</email>
        </developer>
        <developer>
            <id>kmerja</id>
            <name>Klaudio Merja</name>
            <email>klaudio.merja@studenti.unipd.it</email>
        </developer>
        <developer>
            <id>gpadoan</id>
            <name>Giancarlo Padoan</name>
            <email>giancarlo.padoan@studenti.unipd.it</email>
        </developer>
        <developer>
            <id>tsanavia</id>
            <name>Thomas Sanavia</name>
            <email>thomas.sanavia@studenti.unipd.it</email>
        </developer>
    </developers>
    <inceptionYear>2026</inceptionYear>
    <licenses>
        <license>
            <name>Creative Commons Attribution-ShareAlike 4.0 International</name>
            <url>https://creativecommons.org/licenses/by-sa/4.0/</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <log4j.version>2.25.3</log4j.version>
    </properties>

    <dependencies>
        <!-- Servlet API (provided by Tomcat 11) -->
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <version>6.0.0</version>
            <scope>provided</scope>
        </dependency>

        <!-- JSP API (provided by Tomcat 11) -->
        <dependency>
            <groupId>jakarta.servlet.jsp</groupId>
            <artifactId>jakarta.servlet.jsp-api</artifactId>
            <version>3.1.1</version>
            <scope>provided</scope>
        </dependency>

        <!-- JSTL API + implementation -->
        <dependency>
            <groupId>jakarta.servlet.jsp.jstl</groupId>
            <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
            <version>3.0.0</version>
        </dependency>

        <dependency>
            <groupId>org.glassfish.web</groupId>
            <artifactId>jakarta.servlet.jsp.jstl</artifactId>
            <version>3.0.1</version>
            <scope>runtime</scope>
        </dependency>

        <!-- Database -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.3</version>
        </dependency>

        <!-- Password hashing -->
        <dependency>
            <groupId>org.mindrot</groupId>
            <artifactId>jbcrypt</artifactId>
            <version>0.4</version>
        </dependency>

        <!-- JWT -->
        <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>java-jwt</artifactId>
            <version>4.4.0</version>
        </dependency>

        <!-- Jackson (JSON) -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.21.2</version>
        </dependency>

        <!-- Log4j Logging library -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>

    </dependencies>

    <build>
        <finalName>taptable</finalName>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>3.4.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>3.3.1</version>
                </plugin>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.13.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.3.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-war-plugin</artifactId>
                    <version>3.4.0</version>
                </plugin>
                <plugin>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>3.1.2</version>
                </plugin>
                <plugin>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>3.1.2</version>
                </plugin>
                <plugin>
                    <groupId>com.diffplug.spotless</groupId>
                    <artifactId>spotless-maven-plugin</artifactId>
                    <version>3.4.0</version>
                    <configuration>
                        <java>
                            <eclipse>
                                <file>
                                    https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml</file>
                            </eclipse>
                        </java>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>3.12.0</version>
            </plugin>
        </plugins>
    </reporting>
</project>